Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,11 +42,11 @@ jobs:
           exit 1
         }
 
-        - name: Install MongoDB client
-          run: |
-          sudo apt-get update
-          sudo apt-get install -y mongodb-clients
-
+    - name: Install dependencies
+      run: npm install || {
+        echo "Failed to install npm dependencies"
+        exit 1
+      }
 
     - name: Wait for MongoDB to be ready
       run: |
@@ -66,11 +66,9 @@ jobs:
 
     - name: Run tests
       env:
-        MONGODB_URI: mongodb+srv://Tan:1234@assessment.2jgmj.mongodb.net/?retryWrites=true&w=majority&appName=Assessment
+        MONGODB_URI: mongodb://localhost:27017/testDatabase
       run: |
         npm test || {
           echo "Tests failed"
           exit 1
         }
-
-
